# -*- coding: utf-8 -*-
"""12 - Ejercicios Calculo IMC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X5Y1IplSnbWh83TKhAp9P80DdmIqkE0V

1 - En este ejercicio vamos a realizar un programa que nos calcule el índice de masa corporal
de una persona en base a unos datos que nos facilite el usuario por consola. Para ello
debemos solicitar al usuario de nuestro programa los siguientes datos: nombre, edad,
peso y altura.
Debemos crear una clase llamada CalcularIMC(), esta clase tendrá lo siguiente:
- Constructor con argumentos.

Para calcular el imc se utiliza la siguiente formula: 
valor = peso / (altura * altura);

Los mensajes que mostraremos en nuestro programa una vez realizado el calculo serán
los siguientes:
Cuando el programa comience, instanciaremos la clase CalcularIMC() y haremos que el constructor pida las entradas por consola.

si < 16.00

"Hola " + nombre + " tienes delgadez extrema"

si <= 16.00 || valor <= 16.99

"Hola " + nombre + " tienes delgadez moderada"

si <= 17.00 || valor <= 18.49)

"Hola " + nombre + " tienes delgadez aceptable"

si <= 18.50 || valor <= 24.99

"Hola " + nombre + " estas en tu peso"

si <= 25.00 || valor <= 29.99

"Hola " + nombre + " tienes sobrepeso"

si <= 30.00 || valor <= 34.99

"Hola " + nombre + " tienes obesidad de tipo I"

si <= 35.00 || valor <= 40.00

"Hola " + nombre + " tienes obesidad de tipo III"

si no
"no existe clasificacion"
"""



"""2 - Implementar una clase Juego con las siguientes características:

Atributos
- Tiene como atributo público un entero que indica el número de vidas que
le quedan al jugador en la partida actual.

Métodos
- Tiene como método el constructor que acepta un parámetro de tipo entero
que indica el número de vidas iniciales con las que parte el jugador.

- Tiene un método MuestraVidasRestantes que visualiza por pantalla el
número de vidas que le quedan al jugador en la partida actual.

- Además esta clase tiene también el método main que debe realizar lo
siguiente:

- Crea una instancia de la clase Juego indicando que el número de
vidas es 5.

- Resta una vida al valor del atributo con las vidas y vuelve a llamar
a MuestraVidasRestantes.

Clase Juego

- Llama al método MuestraVidasRestantes del objeto creado.

La logica es la siguiente: tenemos que informar al usuario que
introduzca un numero, cada vez que introduzca uno y no acierte
debemos informarle con las palabras mayor o menor que el
numero que hemos guardado en una variable al comienzo del
script, si no acierta vamos restando vidas, en caso de llegar las
vidas a 0 y no hayamos acertado debemos informar al jugado de
que se ha quedado sin vidas
"""

